# Basic GitHub Actions Hello World with Multiple Jobs
name: Hello World Multi-Job Workflow

# Trigger the workflow on push to main branch and pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # First job: Basic greeting
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Say Hello
        run: |
          echo "Hello, World!"
          echo "This is the first job running on Ubuntu"
          date

  # Second job: Environment info
  environment-info:
    runs-on: ubuntu-latest
    needs: hello-job  # This job waits for hello-job to complete
    steps:
      - name: Show environment information
        run: |
          echo "Running environment info job..."
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Current working directory:"
          pwd
          echo "Available space:"
          df -h

  # Third job: Multi-platform hello (runs in parallel with environment-info)
  multi-platform-hello:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: hello-job
    steps:
      - name: Platform-specific hello
        run: |
          echo "Hello from ${{ matrix.os }}!"
        shell: bash

  # Fourth job: Final summary (waits for all previous jobs)
  summary:
    runs-on: ubuntu-latest
    needs: [hello-job, environment-info, multi-platform-hello]
    steps:
      - name: Workflow summary
        run: |
          echo "🎉 All jobs completed successfully!"
          echo "Workflow finished at: $(date)"
          echo "Thanks for running this hello world example!"
